apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: portfolio=docker.io/lkgiovani/lkgiovani-portfolio
    argocd-image-updater.argoproj.io/portfolio.update-strategy: semver
    argocd-image-updater.argoproj.io/portfolio.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/portfolio.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:/envs/production/portfolio/values.yaml
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: oracle-environments
  sources:
    - repoURL: https://github.com/lkgiovani/oracle-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/lkgiovani/oracle-gitops.git
      targetRevision: main
      path: default
      helm:
        valueFiles:
          - $values/envs/production/portfolio/values.yaml
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
