apiVersion: v1
kind: Service
metadata:
  name: controlcar-rabbitmq
  namespace: production
  labels:
    app.kubernetes.io/name: controlcar-rabbitmq
    app.kubernetes.io/part-of: controlcar-deps
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: controlcar-rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
