apiVersion: v1
kind: Service
metadata:
  name: controlcar-redis
  namespace: production
  labels:
    app.kubernetes.io/name: controlcar-redis
    app.kubernetes.io/part-of: controlcar-deps
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: controlcar-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
